server:
  port: 8000
spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    open-in-view: true
  datasource:
    ### MySQL连接信息
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    ### 数据源类别
    type: com.alibaba.druid.pool.DruidDataSource
    ### 初始化大小：最小、最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    ### 配置获取连接等待超时的时间，单位是毫秒
    maxWait: 60000
    ### 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    ### 配置一个连接在池中的最小生存时间，单位是毫秒
    minEvictableIdleTimeillis: 30000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    ### 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSiz: 20
    ### 配置监控统计拦截的filters，去掉后监控界面的SQL无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    ### 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    #useGlobalDataSourceStat: true # 合并多个DruidDataSource的监控数据
  # thymeleaf配置
  thymeleaf:
    # 模板的模式，支持HTML、XML、TEXT、JAVASCRIPT
    mode: HTML5
    # 编码，可不用配置
    encoding: UTF-8
    # 内容类别，可不用配置
    servlet:
      content-type: text/html
    # 开发配置为false，避免修改模板还要重启服务器
    cache: false
    # 配置模板路径，默认是templates，可以不用配置
    prefix: classpath:/templates/
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
  mail:
    host: smtp.126.com
    username: trusause@126.com
    password: IVERSON181003
    ###默认编码
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: false
    # spring.activemq.packages.trust-all:ObjectMessage的使用机制是不安全的
    # ActiveMQ自5.12.2和5.13.0之后，强制Consumer端声明一份可信任的包列表
    # 只有当ObjectMessage中的Object在可信任包内，才能被提取出来。该配置标识信任所有的包
    packages:
      trust-all: true
  ### mongodb配置
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
logging:
  config: classpath:log4j2.xml
  level:
    com:
      example:
        demo:
          dao: debug
mybatis:
  mapper-locations: classpath:/mappers/*Mapper.xml
  type-aliases-package: com.example.demo.dao
### 应用监控配置
management:
#  security:
#    enabled: false #敏感信息访问限制 # SpringBoot2.0已经不使用了
#  endpoint:
#    beans:
#      enabled: false #单个端点配置
  #暴露端点和排除端点的配置
  endpoints:
    web:
      exposure:
        include: "*"  #需要登录才能访问！ * 在yaml 文件属于关键字，所以需要加引号。SpringBoot2.0之后的Actuator只暴露了health和info端点，所以访问其他断点如beans会报404，在SpringBoot的application.yml配置文件中加入这句话暴露所有端点。
        exclude: env,beans  #就算登录了，也不让访问！
#    health:
#      id: myhealth
#  server:
#    servlet:
#      context-path: /manage
#    port: 8081
#  port: #指定访问这些监控方法的端口
#  address: 127.0.0.1 # 指定地址，比如只能通过本机监控，可以设置address: 127.0.0.1
#endpoint:
#  bean:
#    sensitive: false #设置关闭安全限制
